import { MISSION_SOURCE_PATHS } from "../../global/bin/roadmap-mission/preflight.ts";

export const WORK_CAMPAIGN_CONTROLLER_SOURCE_PATHS = [...new Set([
  "global/bin/openspec-archive.ts",
  "global/bin/openspec-change/bounded-falsification.ts",
  "global/bin/openspec-operation-gate.ts",
  "global/bin/portable-process.ts",
  "global/bin/portable-process-supervisor.ts",
  ...MISSION_SOURCE_PATHS.map((relative) => `global/${relative}`),
  "global/bin/roadmap-mission/controller-adapter.ts",
  "global/bin/roadmap-mission/controller-process.ts",
  "global/bin/roadmap-mission/controller-result.ts",
  "global/bin/work-campaign-semantic-executor.ts",
  "global/bin/work-campaign-supervisor.ts",
  "global/bin/work-campaign.ts",
  "global/bin/work-campaign/contracts.ts",
  "global/bin/work-campaign/controller.ts",
  "global/bin/work-campaign/materializer.ts",
  "global/bin/work-campaign/mission-handoff.ts",
  "global/bin/work-campaign/phase-input.ts",
  "global/bin/work-campaign/preflight.ts",
  "global/bin/work-campaign/semantic-executor.ts",
  "global/bin/work-campaign/semantic-playbook.ts",
  "global/bin/work-campaign/semantic-schema.ts",
  "global/bin/work-campaign/state.ts",
  "global/bin/work-campaign/supervisor.ts",
  "global/bin/work-campaign/verification-input.ts",
  "global/model-profiles/quality-independent.json",
  "global/package-lock.json",
  "global/package.json",
  "package.json",
  "tools/model-profile.ts",
  "tools/proofs/lib/opencode-proof-client.ts",
  "tools/proofs/lib/proof-process-cleanup.ts",
  "tools/proofs/work-campaign-playbook.ts",
  "tools/proofs/work-campaign-semantic.ts",
  "tools/proofs/work-campaign-source-paths.ts",
  "tools/proofs/work-campaign.ts",
  "tools/test-work-campaign-controller.ts",
  "tools/test-work-campaign-semantic-executor.ts",
  "tools/test-work-campaign-semantic-playbook.ts",
  "tools/test-work-campaign-supervisor.ts",
])].sort();
