export const TROUBLESHOOTER_FILE = "troubleshooter.md";

type PermissionAction = "allow" | "ask" | "deny";

export const ALLOWED_TROUBLESHOOTER_BASH_RULES: ReadonlyMap<string, PermissionAction> = new Map([
  ["permission.bash.*", "ask"],
  ["permission.bash.git add*", "deny"],
  ["permission.bash.git commit*", "deny"],
  ["permission.bash.git merge*", "deny"],
  ["permission.bash.git rebase*", "deny"],
  ["permission.bash.git push*", "deny"],
  ["permission.bash.git pull*", "deny"],
  ["permission.bash.git fetch*", "deny"],
  ["permission.bash.git reset*", "deny"],
  ["permission.bash.git restore*", "deny"],
  ["permission.bash.git checkout*", "deny"],
  ["permission.bash.git switch*", "deny"],
  ["permission.bash.git clean*", "deny"],
  ["permission.bash.npm install*", "deny"],
  ["permission.bash.npm add*", "deny"],
  ["permission.bash.npm publish*", "deny"],
  ["permission.bash.pnpm install*", "deny"],
  ["permission.bash.pnpm add*", "deny"],
  ["permission.bash.pnpm publish*", "deny"],
  ["permission.bash.yarn install*", "deny"],
  ["permission.bash.yarn add*", "deny"],
  ["permission.bash.yarn publish*", "deny"],
  ["permission.bash.rm *", "deny"],
  ["permission.bash.Remove-Item *", "deny"],
  ["permission.bash.del *", "deny"],
  ["permission.bash.rmdir *", "deny"],
]);

export const ALLOWED_TROUBLESHOOTER_EDIT_RULES: ReadonlyMap<string, PermissionAction> = new Map([
  ["permission.edit.*", "ask"],
  ["permission.edit.*.test.*", "deny"],
  ["permission.edit.*.spec.*", "deny"],
  ["permission.edit.__tests__/**", "deny"],
  ["permission.edit.__snapshots__/**", "deny"],
  ["permission.edit.testdata/**", "deny"],
  ["permission.edit.__fixtures__/**", "deny"],
  ["permission.edit.golden/**", "deny"],
  ["permission.edit.*.golden", "deny"],
  ["permission.edit.*.snap", "deny"],
  ["permission.edit.*_test.*", "deny"],
  ["permission.edit.test_*.*", "deny"],
  ["permission.edit.test-*.*", "deny"],
  ["permission.edit.**/*.test.*", "deny"],
  ["permission.edit.**/*.spec.*", "deny"],
  ["permission.edit.**/__tests__/**", "deny"],
  ["permission.edit.**/__snapshots__/**", "deny"],
  ["permission.edit.**/testdata/**", "deny"],
  ["permission.edit.**/__fixtures__/**", "deny"],
  ["permission.edit.**/golden/**", "deny"],
  ["permission.edit.**/*.golden", "deny"],
  ["permission.edit.**/*.snap", "deny"],
  ["permission.edit.**/*_test.*", "deny"],
  ["permission.edit.**/test_*.*", "deny"],
  ["permission.edit.**/test/**", "deny"],
  ["permission.edit.**/tests/**", "deny"],
  ["permission.edit.**/e2e/**", "deny"],
  ["permission.edit.**/fixtures/**", "deny"],
  ["permission.edit.**/snapshots/**", "deny"],
  ["permission.edit.**/test-library/**", "deny"],
  ["permission.edit.**/test-helpers/**", "deny"],
  ["permission.edit.**/test-*.*", "deny"],
  ["permission.edit.test/**", "deny"],
  ["permission.edit.tests/**", "deny"],
  ["permission.edit.e2e/**", "deny"],
  ["permission.edit.fixtures/**", "deny"],
  ["permission.edit.snapshots/**", "deny"],
  ["permission.edit.docs/feedbacks/**", "allow"],
]);

export const TROUBLESHOOTER_ALLOWED_PERMISSION_KEYS: ReadonlyMap<string, PermissionAction> = new Map([
  ["permission.webfetch", "allow"],
  ["permission.websearch", "allow"],
  ["permission.lsp", "allow"],
]);

export const TROUBLESHOOTER_DENIED_PERMISSION_KEYS: readonly string[] = [
  "task",
  "question",
  "dream_team_*",
  "todowrite",
  "external_directory",
  "doom_loop",
];

export const TROUBLESHOOTER_REQUIRED_TEXT: readonly string[] = [
  "## Runtime Preconditions",
  "prior failed attempts",
  "Allowed write scope",
  "Forbidden paths",
  "Validation gate",
  "read-only triage",
  "not a general developer",
  "Do not write or modify tests",
  "Use web research only",
  "smallest targeted fix",
  "TROUBLESHOOTER_REPORT",
  "Continuation Items",
];
